filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
build:
    tests:
        override:
            -
                command: 'composer test'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
