language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - wget https://phar.phpunit.de/phpunit-4.8.26.phar
  - composer install

script:
  - php phpunit-4.8.26.phar

after_script:
  - wget https://dl.dropboxusercontent.com/u/15117414/test-reporter.phar
  - php test-reporter.phar
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar -v

notifications:
  email: false

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
