language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer install

script:
  - php vendor/bin/phpunit

after_script:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
