language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - composer install

before_script:
  - mkdir build

script:
  - php vendor/bin/phpunit --coverage-clover build/clover.xml tests

after_script:
  - travis_retry php vendor/bin/coveralls -v
